objekte=["2 Jeans", "1 Anzug",
"1 Gürtel",
"3 Hemden",
"2 Unterhemden",
"5 T-Shirts",
"7 Unterhosen",
"7 Paar Socken",
"1 Paar Turnschuhe" ,
"1 Paar Lederschuhe" ,
"1 Paar Winterschuhe",
"1 Paar Sandalen" ,
"1 Mantel" ,
"1 Jacke" ,
"1 Jogginghose" ,
"1 Strickjacke" ,
"1 Wollpullover" ,
"1 Sweatshirt" ,
"1 Computer ",
"1 Tisch" ,
"4 Stühle",
"1 Bett" ,
"1 Regal" ,
"1 Schrank",
"1 Radio" ,
"1 Geldbeutel",
"1 Tasche" ,
"1 Kugelschreiber" ,
"1 Bleistift" ,
"1 Radiergummi" ,
"4 Teller",
"4 Gabeln" ,
"4 Messer" ,
"4 Löffel" ,
"4 Tassen" ,
"2 Töpfe" ,
"1 Pfanne",
"1 Messbecher" ,
"1 Feuerzeug" ,
"1 Zahnbürste" ,
"1 Seife" ,
"1 Shampoo" ,
"1 Zahnpaste" ,
"2 Handtücher" ,
"1 Handy" ,
"1 Taschenmesser" ,
"2 schöne Bilder" ,
"1 dickes Notiz-Buch" ,
"1 Eimer" ,
"1 Mütze" ,
"1 Fahrrad", 
"Tisch", "Gummiente", "Headset", "Franzbrötchen", "Mate", "Alpakas", "Schloss", "Zahn", "Blatt", "Besen", "Staubsauger", "Feuerzeug", "Baby", "Kerze"]